name: Deploy Shipment Manager

on:
  push:
    branches:
      - master

jobs:
  build-push-deploy:
    name: Build, Push and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t zvonkovitanov/shipment-manager:app-production-latest .

      - name: Push Docker image
        run: docker push zvonkovitanov/shipment-manager:app-production-latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /srv/apps/shipment-manager
            ./deploy.sh
